# Generated by Django 4.0.3 on 2022-06-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Enter the product group name', max_length=200, unique=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(help_text='Select or create a group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='shopify.group'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Name of the warehouse', max_length=200, unique=True),
        ),
    ]
