# Generated by Django 4.0.3 on 2022-08-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_alter_group_name_alter_product_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select a group (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='shopify.group'),
        ),
    ]
